const DRINKS = [
  {
    id: 73,
    name: "Milk",
    calories: 38,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Drinks",
  },
  {
    id: 74,
    name: "Juice",
    calories: 30,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Drinks",
  },
  {
    id: 75,
    name: "Coconut Milk",
    calories: 140,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Drinks",
  },
  {
    id: 76,
    name: "Grape Juice",
    calories: 38,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Drinks",
  },
  {
    id: 77,
    name: "Hard Alcohol",
    calories: 100,
    addedToList: false,
    amount: 1,
    amountType: "fl. oz.",
    category: "Drinks",
  },
  {
    id: 78,
    name: "Beer",
    calories: 300,
    addedToList: false,
    amount: 2,
    amountType: "cups",
    category: "Drinks",
  },
  {
    id: 79,
    name: "Wine",
    calories: 125,
    addedToList: false,
    amount: 150,
    amountType: "ml",
    category: "Drinks",
  },
  {
    id: 80,
    name: "Coke",
    calories: 160,
    addedToList: false,
    amount: 12,
    amountType: "fl. oz.",
    category: "Drinks",
  },
  {
    id: 81,
    name: "Gatorade",
    calories: 90,
    addedToList: false,
    amount: 12,
    amountType: "fl. oz.",
    category: "Drinks",
  },
];

export default DRINKS;
