const FATS = [
  {
    id: 53,
    name: "Avocado",
    calories: 32,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 54,
    name: "Oil",
    calories: 125,
    addedToList: false,
    amount: 3,
    amountType: "tsp.",
    category: "Fat",
  },
  {
    id: 55,
    name: "Butter",
    calories: 108,
    addedToList: false,
    amount: 3,
    amountType: "tsp.",
    category: "Fats",
  },
  {
    id: 56,
    name: "Almonds",
    calories: 58,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 57,
    name: "Cashews",
    calories: 55,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 58,
    name: "Chia Seeds",
    calories: 48,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 59,
    name: "Peanuts",
    calories: 56,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 60,
    name: "Pistachios",
    calories: 56,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 61,
    name: "Sunflower Seeds",
    calories: 58,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 62,
    name: "Walnuts",
    calories: 65,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 63,
    name: "Coconut",
    calories: 35,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 69,
    name: "Pecans",
    calories: 32,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 70,
    name: "Sour Cream",
    calories: 90,
    addedToList: false,
    amount: 50,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 71,
    name: "Cheese",
    calories: 41,
    addedToList: false,
    amount: 10,
    amountType: "grams",
    category: "Fats",
  },
  {
    id: 72,
    name: "Cottage Cheese",
    calories: 51,
    addedToList: false,
    amount: 0.5,
    amountType: "cups",
    category: "Fats",
  },
];

export default FATS;
