const FRUITS = [
  {
    id: 29,
    name: "Apples",
    calories: 11,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 30,
    name: "Bananas",
    calories: 17,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 31,
    name: "Blueberries",
    calories: 11,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 32,
    name: "Dates",
    calories: 56,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 33,
    name: "Figs",
    calories: 15,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 34,
    name: "Grapes",
    calories: 20,
    addedToList: false,
    amount: 13,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 35,
    name: "Lemon",
    calories: 5,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 36,
    name: "Mango",
    calories: 12,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 37,
    name: "Oranges",
    calories: 9,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 38,
    name: "Papaya",
    calories: 8,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 39,
    name: "Pears",
    calories: 11,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 40,
    name: "Plum",
    calories: 9,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 41,
    name: "Pineapple",
    calories: 10,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 42,
    name: "Strawberries",
    calories: 6,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 43,
    name: "Watermelon",
    calories: 6,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Fruits",
  },
  {
    id: 44,
    name: "Fruit Cocktail",
    calories: 0.25,
    addedToList: false,
    amount: 50,
    amountType: "cups",
    category: "Fruits",
  },
];

export default FRUITS;
