const GRAINS = [
  {
    id: 45,
    name: "White rice",
    calories: 60,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Grain",
  },
  {
    id: 46,
    name: "Quinoa",
    calories: 150,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Grain",
  },
  {
    id: 47,
    name: "Tortillas",
    calories: 117,
    addedToList: false,
    amount: 50,
    amountType: "grams",
    category: "Grain",
  },
  {
    id: 48,
    name: "Oatmeal",
    calories: 164,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Grain",
  },
  {
    id: 49,
    name: "Spaghetti",
    calories: 104,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Grain",
  },
  {
    id: 50,
    name: "Macaroni",
    calories: 105,
    addedToList: false,
    amount: 0.25,
    amountType: "cups",
    category: "Grain",
  },
  {
    id: 51,
    name: "White Bread",
    calories: 65,
    addedToList: false,
    amount: 25,
    amountType: "grams",
    category: "Grain",
  },
  {
    id: 52,
    name: "Pancakes",
    calories: 89,
    addedToList: false,
    amount: 38,
    amountType: "grams",
    category: "Grain",
  },
];

export default GRAINS;
