const PROTEINS = [
  {
    id: 0,
    name: "Salmon",
    calories: 58,
    addedToList: false,
    amount: 5,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 1,
    name: "Chicken",
    calories: 61,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 2,
    name: "Beef",
    calories: 70,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 3,
    name: "Duck",
    calories: 94,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 4,
    name: "Pork",
    calories: 55,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 5,
    name: "Turkey",
    calories: 53,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 6,
    name: "Chicken Breast",
    calories: 48,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 7,
    name: "Bacon",
    calories: 114,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 8,
    name: "Sausage",
    calories: 85,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 9,
    name: "Hot Dog",
    calories: 80,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 10,
    name: "Whitefish",
    calories: 50,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 11,
    name: "Chickpeas",
    calories: 100,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 12,
    name: "Beans",
    calories: 95,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 13,
    name: "Tofu",
    calories: 21,
    addedToList: false,
    amount: 5,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 14,
    name: "Lentils",
    calories: 100,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
  {
    id: 15,
    name: "Yogurt",
    calories: 17,
    addedToList: false,
    amount: 1,
    amountType: "ounces",
    category: "Protein",
  },
];

export default PROTEINS;
