const VEGETABLES = [
  {
    id: 16,
    name: "Broccoli",
    calories: 7,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 17,
    name: "Carrots",
    calories: 8,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 18,
    name: "Garlic",
    calories: 29,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 19,
    name: "Mushrooms",
    calories: 4,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 20,
    name: "Olives",
    calories: 23,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 21,
    name: "Onions",
    calories: 8,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 22,
    name: "Potatoes",
    calories: 15,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 23,
    name: "Sweet Potatoes",
    calories: 17,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 24,
    name: "Celery",
    calories: 2,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 25,
    name: "Corn",
    calories: 73,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 26,
    name: "Eggplant",
    calories: 5,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 27,
    name: "Lettuce",
    calories: 4,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables",
  },
  {
    id: 28,
    name: "Peas",
    calories: 9,
    addedToList: false,
    amount: 20,
    amountType: "grams",
    category: "Vegetables"
  },
];

export default VEGETABLES;
